#include "cocos2d.h"
using namespace cocos2d;
class GameScene : public cocos2d::Layer{
public:
	static cocos2d::Scene* createScene();
	virtual bool init();
	//virtual void onExit();
	void menuCloseCallback(cocos2d::Ref* pSender);
	void menuMusicCallback(cocos2d::Ref* pSender);
	void readTexture();
	void addMogu();
	void addListence();
	void bearMoveEnd();
	void addCaotiao();
	void gundong();
	void pangduanbianjie(float t);
	void moguGundong();
	void deleteVector();
	void addCrash(float t);
	//void addCrash();
	void addDaoJuBao();
	void addJinBi();
	void addjinbigundong();
	void addjishu();
	void switchToLayer(cocos2d::Ref* pSender);
	void switchToHelpLayer(cocos2d::Ref* pSender);
	
	void switchScene();
    void start();
	void jinbiMoveEnd();
	PhysicsWorld* m_world;
	void setPhyWorld(PhysicsWorld* world) { m_world = world; };
	virtual bool onContactBegin(PhysicsContact& contact);
	void onContactSeperate(PhysicsContact& contact);
	void addDaoju();
	GameScene();
	void OnTouchHuJia(float t);
	void removelabel(float t);
	void stopAllAction(float t);
	void adddaojuxiaoguo();
	void xiaoguoshixian(float t);
	void addMusic();
	CC_SYNTHESIZE_RETAIN(cocos2d::CCSprite*, _bear, Bear);
	CC_SYNTHESIZE_RETAIN(cocos2d::CCAction*, _heroAction, HeroAction);
	CC_SYNTHESIZE_RETAIN(cocos2d::CCAction*, _moveAction, MoveAction);
private:
	bool _bearMoving;
	float beginX;
	float beginY;
	int runRand;
	int m;
	bool isPause;
//	int jinbiNum;
	Sprite* hero;
	bool isOnTouch;
	float levelNum;
	int moguNum;
	int jinbiNum;
	int scoreNum=0;
	MoveTo* moguMoveTo;
	MoveTo* jinbiMoveTo;
	LabelTTF* moguNumLabel;
	LabelTTF* jinbiNumLabel;
	LabelTTF* scoreLabel;
	Vector <SpriteFrame*> heroAnimFrames;
	Vector<Sprite*> daojubaos;
	Vector<Sprite*> mogus;
	Vector<Sprite*> caotiaos1;
	Vector<Sprite*> caotiaos2;
	Vector<Sprite*> caotiaos3;
	Vector<Sprite*> caotiaos4;
	Vector<Sprite*> caotiaos;
	Vector<Sprite*> jinbis;
	Vector<Sprite*> gamedaojus;
	int jinbishuzu[20];
	float oldTime;
	float newTime;
	int tagMove = 0;
	bool isOnHuJia = false;
	bool HavaDaHuaiDan = false;
	Sprite* bg_1;
	Sprite* bg_2;
	CREATE_FUNC(GameScene);
};